GET http://localhost:3000/expenses


###

POST http://localhost:3000/expenses
Content-Type: application/json

{
	"name": "salary",
	"location": "longos",
	"amount": "600",
	"date": "2022-08-12",
	"type": "in"
}

###

DELETE http://localhost:3000/expenses/62f41e63e77d4c2d51033390

###

PATCH  http://localhost:3000/expenses/62f4202668c30d05cd681d43
Content-Type: application/json

{
	"name": "hi",
	"location": "best buy",
	"amount": "1000",
	"date": "08/10/2022",
	"type": "out"
}